### ISSUE TITLE
Configurable grace period for TaskRun pods in ImagePullBackOff

### ISSUE THREAD

**Issue by rinckm** [tektoncd/pipeline#5987] opened 2023-01-12 07:41 UTC
### Feature request

Introduce a configurable grace period for TaskRun pods to be in ImagePullBackOff without failing the TaskRun.

### Use case

We are using Tekton to execute TaskRuns. In our use case images for TaskRun pods cannot be pulled directly because container registry credentials must not exist in the namespace for security reasons. Instead, there’s another component in the cluster that pulls images for TaskRun pods. In case of delays in image pulling a TaskRun’s pod may be subject to ImagePullBackOff and recovers after the image has been provisioned on the respective node.

With PR #4921 (fail TaskRuns on ImagePullBackOff) we now see sporadically failing TaskRuns.

We propose to introduce a configurable grace period where ImagePullBackOff is tolerated and does not fail a TaskRun.

**Comment by jerop** [comment] 2023-01-12 12:42
@rinckm thank you for sharing your use case for this feature request; we had discussed supporting this as future work for [TEP-0092](https://github.com/tektoncd/community/blob/main/teps/0092-scheduling-timeout.md#continue-timeout-until-running) -- the TEP has not been implemented yet, we welcome contributions in implementing it

cc @bobcatfish @Aleromerog 

/help-wanted

**Comment by shuheiktgw** [comment] 2023-01-22 23:43
Hi, may I try implementing this feature? 👋 
/assign

**Comment by afrittoli** [comment] 2023-01-24 11:47
Hello @shuheiktgw, thank you for offering to implement this, that would be great. 
The TEP already exists and is in an implementable state.
@jerop @bobcatfish @Aleromerog FYI

**Comment by jerop** [comment] 2023-01-24 15:49
@shuheiktgw thank you for offering to implement -- @EmmaMunley has also started looking into this issue, maybe you can collaborate?

**Comment by shuheiktgw** [comment] 2023-01-24 22:25
Sure, I'm happy to collaborate🙂  Hi @EmmaMunley, how is the implementation going so far? I'd appreciate it if you would push any WIP changes so that I can see if there is anything I can help!

**Comment by EmmaMunley** [comment] 2023-01-25 22:41
Hi @shuheiktgw! Sure! I am working on implementing the scheduling timeout feature first as part of this issue: [#4078](https://github.com/tektoncd/pipeline/issues/4078).

**Comment by pritidesai** [comment] 2024-02-05 20:03
Thanks @dibyom for reopening this issue.

We are running into this issue and looking for a potential solution.

The issue is, the node where the pod is scheduled often experiences registry rate limit. The image pull failure because of the rate limit returns the same warning (`reason: Failed and message: ImagePullBackOff`). The pod can potentially recover after waiting for enough time until the cap is expired. Kubernetes can then successfully pull the image and bring the pod up.

We have this issue reported by multiple end users:  https://github.com/tektoncd/pipeline/issues/7184

**The problem statement for this issue is to be able to continue waiting when a step or sidecar container reports the container is waiting with `ImagePullBackOff`.**

[TEP-0092](https://github.com/tektoncd/community/blob/main/teps/0092-scheduling-timeout.md#continue-timeout-until-running) proposed to solve this issue. [TEP-0092](https://github.com/tektoncd/community/blob/main/teps/0092-scheduling-timeout.md) is now marked as `deferred` while proposing [TEP-0132](https://github.com/tektoncd/community/blob/main/teps/0132-queueing-concurrent-runs.md).   [TEP-0132](https://github.com/tektoncd/community/blob/main/teps/0132-queueing-concurrent-runs.md) has much wider scope and focuses on proposing a generic solution for creating a `queue` of `pipelineRun`/`taskRuns`/etc. Until we resume [TEP-0132](https://github.com/tektoncd/community/blob/main/teps/0132-queueing-concurrent-runs.md), I would like to check with the community to propose a solution for this particular problem statement. Thoughts? @tektoncd/core-maintainers

**Comment by pritidesai** [comment] 2024-02-05 21:36
Revising the [TEP-0132](https://github.com/tektoncd/community/blob/main/teps/0132-queueing-concurrent-runs.md) , it might not be able to resolve this particular issue as the taskrun controller treats `ImagePullBackOff` as permanent error. To overcome this limitation, we need a solution to not just avoid `ImagePullBackOff` as there can be other non-tekton resource in the cluster causing rate limit problem. We need a solution (opt-in) to avoid treating `ImagePullBackOff` as a permanent error.

**Comment by vdemeester** [comment] 2024-07-01 07:54
Given that #7666 is merged (see [docs](https://github.com/tektoncd/pipeline/blob/main/docs/additional-configs.md#taskruns-with-imagepullbackoff-timeout)), I'll go ahead and close this.

**Closed by vdemeester** 2024-07-01 07:54 UTC
Labels: kind/feature, help wanted
