### ISSUE TITLE
Can we restart taskrun or pipelinerun when the task or pipeline complete or failed

### ISSUE THREAD

**Issue by zxDiscovery** [tektoncd/pipeline#664] opened 2019-03-24 00:59 UTC
# Expected Behavior

The `tektoncd/pipeline` can restart their task.

# Actual Behavior

I always delete the current complete `taskrun` and re-apply this `taskrun` to restart the `task`.

So I just want to know does the `tektoncd/pipeline` has the feature to restart the `task`?

# Additional Info
I also log an issue for `knative/build` https://github.com/knative/build/issues/580

**Comment by hrishin** [comment] 2019-03-27 12:24
Thanks! for reporting this issue @zxDiscovery :+1:. Sorry to say this, as far as I know, its not possible :(.

The disucssion is going this issue https://github.com/tektoncd/pipeline/issues/664. We would love to hear some ideas or paposals to solve this problem :)

Does that helps?

**Comment by vdemeester** [comment] 2019-03-28 07:42
Closing this one as a duplicate of #685 (@hrishin you linked the wrong issue :nerd_face:)
/close

**Closed by vdemeester** 2019-03-28 07:42 UTC
