### ISSUE TITLE
[v0.44.x] The webhook is extremely noisy when using resolvers

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#6442] opened 2023-03-28 08:49 UTC
# Expected Behavior

When using resolvers, the webhook has a a decent amount of logs, and only logs when there is "normal activities".

# Actual Behavior

When using resolvers, the webhook becomes very noisy — a line per second without any new objects. Most logs are about conversion :
```
conversion failed to version v1alpha1 for type [kind=ResolutionRequest group=resolution.tekton.dev version=v1beta1] -  v1beta1 is the highest known version, got: *v1alpha1.ResolutionRequest"
```

# Steps to Reproduce the Problem

1. Deploy `v0.44.x`
2. `kubectl create -f ./examples/v1beta1/pipelineruns/pipelinerun.yaml`
3. Look at the webhook  logs

# Additional Info

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.44.x
```

The logs are the following:

```
{"severity":"error","timestamp":"2023-03-28T08:44:15.745Z","logger":"tekton-pipelines-webhook","caller":"conversion/conversion.go:59","message":"Conversion failed","commit":"0e9e4b9-dirty","uid":"18949c63-5109-45b7-8900-8d07a10cc315","desiredAPIVersion":"resolution.tekton.dev/v1alpha1","error":"conversion failed to version v1alpha1 for type [kind=ResolutionRequest group=resolution.tekton.dev version=v1beta1] -  v1beta1 is the highest known version, got: *v1alpha1.ResolutionRequest","stacktrace":"knative.dev/pkg/webhook/resourcesemantics/conversion.(*reconciler).Convert\n\tknative.dev/pkg@v0.0.0-20230221152827-2d84369c105d/webhook/resourcesemantics/conversion/conversion.go:59\nknative.dev/pkg/webhook.conversionHandler.func1\n\tknative.dev/pkg@v0.0.0-20230221152827-2d84369c105d/webhook/conversion.go:66\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2487\nknative.dev/pkg/webhook.(*Webhook).ServeHTTP\n\tknative.dev/pkg@v0.0.0-20230221152827-2d84369c105d/webhook/webhook.go:263\nknative.dev/pkg/network/handlers.(*Drainer).ServeHTTP\n\tknative.dev/pkg@v0.0.0-20230221152827-2d84369c105d/network/handlers/drain.go:113\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2947\nnet/http.(*conn).serve\n\tnet/http/server.go:1991"}
```

I didn't try it out on `main` nor on previous LTS yet.

**Comment by lbernick** [comment] 2023-03-28 20:50
This looks like it may be a duplicate of https://github.com/tektoncd/pipeline/issues/6075

**Comment by vdemeester** [comment] 2023-03-29 03:51
@lbernick it is indeed 😅

**Closed** 2023-04-11 10:36 UTC
Labels: kind/bug
