### ISSUE TITLE
Can't pull docker images anymore.

### ISSUE THREAD

**Issue by scboffspring** [tektoncd/pipeline#3082] opened 2020-08-10 12:26 UTC
# Expected Behavior

Image would be pulled successfully.

# Actual Behavior

```
Failed to pull image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init:v0.11.2@sha256:ced427e48b143bc821aedd4a0936fa2caef3f208d70efe68ccba786c12b2c943": rpc error: code = Unknown desc = Error response from daemon: pull access denied for gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init, repository does not exist or may require 'docker login': denied: Permission denied for "sha256:ced427e48b143bc821aedd4a0936fa2caef3f208d70efe68ccba786c12b2c943" from request "/v2/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init/manifests/sha256:ced427e48b143bc821aedd4a0936fa2caef3f208d70efe68ccba786c12b2c943".
```

# Additional Info

It also looks like the release file  (https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml) cannot  be retrieved (403 error)./

![image](https://user-images.githubusercontent.com/2176689/89782384-17e28380-db0d-11ea-9827-c49449ed8a5f.png)

**Comment by sbwsg** [comment] 2020-08-10 13:19
Thanks for the issue report!  I'm going to close this as duplicate of https://github.com/tektoncd/pipeline/issues/3083 because I've already responded there and don't want to duplicate comments between the two as we work to resolve this.  For anyone looking for more info, please follow #3083 - cheers and apologies for this interruption!

**Closed by sbwsg** 2020-08-10 13:19 UTC
Labels: kind/bug
