### ISSUE TITLE
Support go modules

### ISSUE THREAD

**Issue by poy** [tektoncd/pipeline#1538] opened 2019-11-07 23:01 UTC
# Expected Behavior
Repo uses go modules

# Actual Behavior
Repo uses dep

# Additional Info

Kubernetes has transitioned to go modules and the go community is pushing more things towards this. I think we should consider doing the same.

**Comment by vdemeester** [comment] 2019-11-08 08:33
This is a duplicate of  #1315 more or less, we should keep only one of those issue

**Comment by bobcatfish** [comment] 2020-01-06 16:26
@wlynch maybe we can close this issue? @vdemeester mentioned we might want to open another issue re. continuing to vendor or not but otherwise it seems like go module support is done? 🎉

**Comment by bobcatfish** [comment] 2020-02-18 15:55
Current state:
- CI uses vendor/ dir and doesn't download (~50% faster than pulling)
- We support go modules, but you are still expected to keep the vendor dir in sync

We feel like this is okay for now

**Comment by bobcatfish** [comment] 2020-03-16 15:12
https://github.com/tektoncd/pipeline/issues/2065 is continuing the vendor directory conversation, closing this issue.

**Closed by bobcatfish** 2020-03-16 15:12 UTC
Labels: kind/feature, priority/important-longterm, triage/duplicate
