### ISSUE TITLE
Intermittent "InvalidTaskResultReference" when running tasks with big results

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#4529] opened 2022-01-27 21:16 UTC
We've been seeing an increasing number of teams reporting `InvalidTaskResultReference` problems in pipelines that might otherwise run successfully. We are seeing this infrequently (1 in 40) but we've now seen it a number of different unrelated pipelines. Something like this...

---
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/541119/151443715-e9b26909-22c9-4a18-8d38-e3802bf05b83.png">

---

The "results" in question are generally large-ish -- 2K+ (correction here thanks @pritidesai) and are present when we look ;)

We suspect that what's happening is that there is a race somewhere. Perhaps a race between the "next" task running and the current TaskRun being updated with the Result. That's just a guess, but does this seem possible/likely?

I'll try to create a good test-case but this sort of race condition is not easy to get to happen on demand although it clearly is occurring with some regularity.

**Comment by pritidesai** [comment] 2022-02-07 20:25
I think its very likely possible and surprised to see this happening intermittently.

The `taskRun` status is updated once all containers in the pod have terminated (pod succeeded or failed).

https://github.com/tektoncd/pipeline/blob/6cb0f4ccfce095495ca2f0aa20e5db8a791a1afe/pkg/pod/status.go#L109-L115

`updateCompletedTaskRunStatus` includes updating the condition and competition time.

But there is [more](https://github.com/tektoncd/pipeline/blob/6cb0f4ccfce095495ca2f0aa20e5db8a791a1afe/pkg/pod/status.go#L117-L136) updated done after updating the status to **completed**.

In the end, the taskRun status is updated with the results:

https://github.com/tektoncd/pipeline/blob/6cb0f4ccfce095495ca2f0aa20e5db8a791a1afe/pkg/pod/status.go#L138

So if its possible for the pipelineRun controller to pick up the completed status before the task results are populated, its also possible to run into this issue.

**Comment by pritidesai** [comment] 2022-02-07 20:32
@lbernick thanks for adding the priority 👍  Let me know if you want to take a stab at it else I am happy to try fixing it 🙏 

/assign

**Comment by vdemeester** [comment] 2022-04-28 14:51
/assign 
I think I know why this is happening, I'll create an additional issue around this, but in a gist, it's because of the termination message behavior in k8s with multiple containers.

> The total size of termination messages of all containers in a pod cannot exceed 12 KB. If the total size exceeds 12 KB, the state manager of Kubernetes sets a limit on the termination message sizes. For example, if a pod contains four InitContainers and eight application containers, the state manager limits the termination message of each container to 1 KB. This indicates that only the first 1 KB of the termination message of each container is intercepted.

**Comment by vdemeester** [comment] 2022-04-28 15:45
@skaegi @pritidesai @chitrangpatel see https://github.com/tektoncd/pipeline/issues/4808

**Comment by vdemeester** [comment] 2022-05-04 15:43
@skaegi https://github.com/tektoncd/pipeline/pull/4826 has a "regression" test that reproduce this constantly between 0.32 and 0.35 😉

**Comment by dibyom** [comment] 2022-06-14 16:45
Closing in favor of #4808 which tracks larger results in general

**Closed by dibyom** 2022-06-14 16:45 UTC
Labels: kind/bug, priority/important-soon
