### ISSUE TITLE
Support 'from' usage in pipeline conditions

### ISSUE THREAD

**Issue by jkljf** [tektoncd/pipeline#1499] opened 2019-10-30 14:13 UTC
# Expected Behavior
On generating the pod for conditions, if 'from' is used for the condition's resource, the pod could mount to that resource (e.g. /pvc/<resource name>) then copy to condition resource's workspace.
This is similar to Task usage in the pipeline.
# Actual Behavior
No support 'from', any Git resource declared for the condition will be handled as normal Git fetch.
# Steps to Reproduce the Problem
1. Define a normal Condition check with resource type Git
2. Use that Condition in the pipeline, expect 'from' can be used

# Additional Info

**Comment by bobcatfish** [comment] 2019-10-31 15:49
Thanks for opening this @jkljf ! I think this is a duplicate of https://github.com/tektoncd/pipeline/issues/1256 so I'm going to close it, but I'm going to copy some of your description into there also :D

**Closed by bobcatfish** 2019-10-31 15:49 UTC
