### ISSUE TITLE
not able to pull image from private harbor registry.

### ISSUE THREAD

**Issue by 288milan** [tektoncd/pipeline#6276] opened 2023-03-02 16:22 UTC
not able to pull image from private harbor registry.
I already created secret and attached it to the service account.
is there any additional settings need to be done for harbor registry?
Its working with normal pod by using imagepullsecret. which means my password is correct.
i am also able to use public images in the task from the same registry.so my url is also correct.

this is the error i got while try to pull image by the task.

ErrImagePull (rpc error: code = Unknown desc = failed to pull and unpack image "harbor.xxxxx.com/tekton-test/tekton-test:gitclone": failed to resolve reference "harbor.xxxxx.com/tekton-test/tekton-test:gitclone": pulling from host harbor.xxxxx.com failed with status code [manifests gitclone]: 401 Unauthorized)

do u guys have any idea about this error?
is there any change need to be done to the secret's annotation "tekton.dev/docker-0" ?
is there any way to directly attach the imagepullsecret in task itself ?

**Comment by afrittoli** [comment] 2023-03-03 11:47
@288milan I would suggest closing this as a duplicate of #3604 , but please let us know if the solution provided works for you

**Closed as completed** 2023-07-31 13:13 UTC
Labels: kind/bug, lifecycle/rotten
