### ISSUE TITLE
Missing documentation about updating

### ISSUE THREAD

**Issue by vas-dev-ops** [tektoncd/pipeline#2026] opened 2020-02-10 11:25 UTC
# Expected Behavior

To find in the documentation a paragraph about how to install the new versions of tekton.

# Actual Behavior

There is no documentation about the installation of the new releases

**Comment by bobcatfish** [comment] 2020-02-26 15:20
I think this is a duplicate of https://github.com/tektoncd/pipeline/issues/1222 (plz re-open if not!)

**Closed by bobcatfish** 2020-02-26 15:20 UTC
Labels: kind/documentation
