### ISSUE TITLE
Add support for knowing what pipelinerun/taskrun is running the task steps

### ISSUE THREAD

**Issue by ricardochimal** [tektoncd/pipeline#2747] opened 2020-06-03 21:32 UTC
# Expected Behavior

I can tell within my task environment which pipelinerun and/or taskrun it's running for

# Actual Behavior

Currently I don't see a way for my task steps to know what the pipelinerun or taskrun is associated with it.  My use case is that I emit some output to a chatbot but would like to reference the run as part of the message to make it easier for other people to check the logs of the pipelinerun.

How this is exposed to the container could be special new variables (i.e. `$(tekton.pipelinerun-id)`),  a workspace w/ a directory structure (i.e. `/proc/` lite), environment variables, or something like the ec2 metadata api (seems a bit over the top but don't know?).

# Additional Info

- Kubernetes version: v1.15
- Tekton Pipeline version: v0.12.0

**Comment by sbwsg** [comment] 2020-06-04 14:06
Thanks for the issue!  I'm going to close this a duplicate of https://github.com/tektoncd/pipeline/issues/1522 since I think it's discussing the same problem.  Feel free to reopen if you think this issue is different enough to warrant its own problem statement though.

**Closed by sbwsg** 2020-06-04 14:06 UTC
