### ISSUE TITLE
When using ${variable} in containerTemplate, it is not working

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/pipeline#811] opened 2019-04-29 16:34 UTC
# Expected Behavior

Templating in containerTemplate should work.

# Actual Behavior

Templating in containerTemplate is not working.

# Steps to Reproduce the Problem

1. Create a Cluster resource.
```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cluster-details
spec:
  type: cluster
  params:
  - name: url
    value: " "
  - name: name
    value: " "
  - name: username
    value: " "
  - name: token
    value: " "
  - name: cadata
    value: " "
```
2. Create a task using cluster resource.
```
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-openshift-command-clusterresource
spec:
  containerTemplate:
    env:
      - name: "KUBECONFIG"
        value: "/workspace/${inputs.resources.clusterdetails.name}/kubeconfig"
  inputs:
    resources:
      - name: clusterdetails
        type: cluster
  steps:
    - name: foo
      image: ubuntu
      command:
        - /bin/bash
      args: ["-c", "env"]
```
3. Create task run for the task
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: task-run-openshift-command-clusterresource
spec:
  taskRef:
    name: task-openshift-command-clusterresource
  inputs:
    resources:
      - name: clusterdetails
        resourceRef:
          name: cluster-details
```
4. Check the logs of the step, it will show something like
```
oc logs task-run-openshift-command-clusterresource-pod-4645e9 -c build-step-foo
KUBECONFIG=/workspace/${inputs.resources.clusterdetails.name}/kubeconfig
```
# Additional Info

Tekton version v0.3.1

**Comment by abayer** [comment] 2019-04-29 16:47
Interesting - this is actually an enhancement, not a bug, fwiw, since variable templating has to be explicitly enabled for a field. This raises a question though - variable templating can only be done on explicitly specified string fields, which in the case of steps (i.e., `Container`s, so the logic we could trivially reuse for `containerTemplate`) currently means `Name`, `Image`, `Args`, `Env` values, `Command`, and `Name`, `MountPath`, and `SubPath` for `VolumeMounts`. Do we want to try to do a more general approach that, say, traversed the `Container` for all string fields and all fields that are structs with their string fields, etc? cc @bobcatfish @vdemeester for your thoughts.

**Comment by bobcatfish** [comment] 2019-05-21 12:09
> Do we want to try to do a more general approach that, say, traversed the Container for all string fields and all fields that are structs with their string fields, etc?

Yeah, I'm into that! I think it's confusing to only be doing it for a few fields.

**Comment by abayer** [comment] 2019-05-21 12:12
That's definitely doable, for sure.

**Comment by bobcatfish** [comment] 2019-06-13 16:59
Note https://github.com/tektoncd/pipeline/pull/982 is expanding the scope of values that can be templated, but not as broadly as we're suggesting here!

**Comment by vdemeester** [comment] 2019-06-26 14:49
#1006 is in, this should be fixed :angel: 
/close

**Closed by vdemeester** 2019-06-26 14:49 UTC
Labels: good first issue, help wanted, kind/feature, meaty-juicy-coding-work
