### ISSUE TITLE
Workspace default to `empty Dir`

### ISSUE THREAD

**Issue by hakuna-matatah** [tektoncd/pipeline#4173] opened 2021-08-18 20:19 UTC
### Feature request

Today we need to define workspace  as part of triggertemplate or Task or pipeline:
```
      workspaces:
      - name: source
        emptyDir: {}
      - name: config
        emptyDir: {}
      - name: results
        emptyDir: {}
````

### Use case

Could we have it defaulted to `emptyDir` when nothing is specified ?

**Comment by sbwsg** [comment] 2021-08-19 14:05
Bringing over my comment from Slack:

You can configure `emptyDir` to be the default for taskruns today.  We don't have a general approach like this for pipelineruns tho.

Edit the `config-defaults` configmap in your `tekton-pipelines namespace and set the `default-task-run-workspace-binding` to be the workspace binding you want (e.g. `emptyDir: {}`)

Example: https://github.com/tektoncd/pipeline/blob/main/config/config-defaults.yaml#L66-L70

**Comment by sbwsg** [comment] 2021-08-19 14:07
Also I just realised we do already have a feature ticket for this.

Closing as a duplicate of https://github.com/tektoncd/pipeline/issues/2595

**Closed by sbwsg** 2021-08-19 14:07 UTC
Labels: kind/feature

**Comment by hakuna-matatah** [comment] 2021-08-19 15:04
Thanks for the details. I'm looking for something in pipelineruns. This ticket would help - https://github.com/tektoncd/pipeline/issues/2595
