### ISSUE TITLE
why don`t make step as a kind of resource,just like task,pipeline, so we can use step at anywhere too.

### ISSUE THREAD

**Issue by gitupxm163** [tektoncd/pipeline#3009] opened 2020-07-24 14:48 UTC
why don`t make step as a kind of resource,just like task,pipeline, so we can use step at anywhere too.

**Comment by danielhelfand** [comment] 2020-07-24 15:04
@gitupxm163 There is actually an open issue for this (#1260). I unfortunately never got around to putting together a proposal for it, but there has been some activity around it if you would like to weigh in on the discussion. I think the original thought process when creating Tekton would be that Tasks would be the easiest way to reuse resources as mentioned in the issue. However, I also see the validity in making steps reusable via some type of ref property. Please feel free to add any use cases or ideas you have in the original issue.

**Comment by pritidesai** [comment] 2020-07-24 16:44
@gitupxm163 @danielhelfand trying to understand the use case and the value this would add. Will your use case suffice by creating a script and reusing it:

```
steps:
- image: ubuntu
  script: |
    #!/usr/bin/env bash
    /workspace/path-to-script/my-script.sh  # provided by an input resource
```

Here, `my-script.sh` can be part of the `GitHub` repo and the repo is cloned into workspace.

**Comment by sbwsg** [comment] 2020-07-24 19:49
I'm going to close this as a duplicate of https://github.com/tektoncd/pipeline/issues/1260.

**Closed by sbwsg** 2020-07-24 19:49 UTC

**Comment by danielhelfand** [comment] 2020-07-24 20:34
@pritidesai I think the main issue is the design of Tekton itself is supposed to promote reusability, and yet step properties need to be fully written out as part of a Task instead allowing them to be easily shared a reused. 

Why should a user need to define this step's image, command or script, resource requests/limits, securityContext, etc. again if a step already exists and has these properties defined? I think steps should somewhat mirror the design of Tasks in that they should be able to accept values at run time and be easily shared via a ref property. It's really in my mind about promoting DRY and reducing copy and paste as a practice for reusing steps.

That and the ability to easily define a step that runs a script or quick command without having to create a whole Task definition would also be interesting.
