### ISSUE TITLE
Deleting Pipeline should delete PipelineRuns

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/pipeline#2223] opened 2020-03-13 14:31 UTC
# Expected Behavior

When deleting a `Pipeline`, all `PipelineRun` that refer to the pipeline should get deleted too since they refer to an non-existing pipeline.

# Actual Behavior

Deleting a `Pipeline` leaves orphaned `PipelineRun` 

# Steps to Reproduce the Problem

1. Create a pipeline
2. Run `tkn p start` to start the pipeline
3. Run `tkn p delete` to delete the pipeline
4. Run `tkn pr list` to see the orphaned pipelineruns still exist without the actual pipeline

**Comment by danielhelfand** [comment] 2020-03-13 14:42
Should this be an expected default behavior? 

There is a way through the CLI to delete PipelineRuns associated with a Pipeline, but I feel that should be left to the user to decide and not assume PipelineRuns shouldn't be preserved. Why would deleting the Pipeline imply that those PipelineRuns don't have meaningful information?

This is what happens for TaskRuns when a PipelineRun is deleted, so there is some of this behavior that is similar that already exists, but I am curious about the reasoning.

**Comment by siamaksade** [comment] 2020-03-13 15:09
IMO that's the expected behaviour for users that have tried any other CI/CD platform. Deleting the pipeline always removes the executions of those pipelines in other platforms.

**Comment by bobcatfish** [comment] 2020-03-13 15:15
I'm also not 100% sure we'd want this to be the default behavior but could go either way! Especially since we can't really guarantee that any particular kubernetes cluster will stick around for long anyway.

Note that in the context of the work done in https://github.com/tektoncd/pipeline/issues/1839 to store Tasks + Pipelines completely outside the cluster (e.g. in an image registry or in git) there may not be a Pipeline or Task associated with the Run in the cluster at all.

**Comment by bobcatfish** [comment] 2020-03-13 15:16
(Added to the next working group agenda to discuss!)

**Comment by bobcatfish** [comment] 2020-03-13 15:22
Note looks like possibly a duplicate of https://github.com/tektoncd/pipeline/issues/102

**Comment by danielhelfand** [comment] 2020-03-13 15:41
> I'm also not 100% sure we'd want this to be the default behavior but could go either way! Especially since we can't really guarantee that any particular kubernetes cluster will stick around for long anyway.

Maybe this is something that could be made configurable, but I do guess I lean towards not having it as the default behavior. That said, I do think the use case makes sense definitely.

**Comment by siamaksade** [comment] 2020-03-13 15:44
Making it configurable makes sense to me. But it would be inconsistent with the cascading deletes from PipelineRun to TaskRun and pods.

**Comment by danielhelfand** [comment] 2020-03-13 15:54
> Making it configurable makes sense to me. But it would be inconsistent with the cascading deletes from PipelineRun to TaskRun and pods.

Yeah, whatever the preferred route to go here is that there should be consistency. I think what this has shifted to is what the default should be.

**Comment by a-roberts** [comment] 2020-03-18 13:06
I'm +1 on this being configurable (but then, how? Should this be where the discussion goes?) - some considerations (@bobcatfish just mentioned these as well on the WG call 😸 )

- You want to view old PipelineRun details and you've just moved (let's say, renamed) that super important PIpeline you've had - important for traceability
versus
- You're developing and you really don't care for your PIpelineRuns, so they're cool to be thrown away

Having loads of PipelineRuns is a pain if you end up with loads of PVCs lingering so can definitely see why this is a thing to consider (at least this is what I always see using dynamic provisioning).

When you say TaskRuns are removed when PipelineRuns are removed, that doesn't lead to any loss of traceability does it? As they're made from the PipelineRuns itself are they not?

**Comment by bobcatfish** [comment] 2020-03-18 13:18
Copying in some notes from the WG:

* https://github.com/tektoncd/pipeline/issues/2045 (for the having the def somewhere) — and linked issues
* When storing Tasks/Pipelines Resources in OCI registries, the cluster may not be the source of truth anyway (https://github.com/tektoncd/pipeline/issues/1839)
  * Have proposed embedding Pipelines + Tasks in Runs so we know what they are/were
* Use case: Dashboard doesn’t support representing PipelineRuns when Pipeline is gone?
* What about when Pipeline is embedded in PipelineRun?
* What about the fact that deleting a PipelineRun deletes related TaskRuns?
  * Maybe different because PipelineRun creates TasksRuns, i.e. explicit ownership
* Perhaps provide an helper to delete pipelinerun on pipeline deletion?
* Annotate pipelineruns that should not be deleted

My preference after the conversation is:
* Do not delete PipelineRuns by default
* Provide some kind of mechanism (maybe a separate tool, maybe part of the CLI) to do this, maybe using annotations to decide if some Runs should be preserved

**Closed** 2020-08-13 18:31 UTC
Labels: kind/feature, lifecycle/rotten
