### ISSUE TITLE
Resource Cleanup / Long-Term Storage

### ISSUE THREAD

**Issue by Fabian-K** [tektoncd/pipeline#1646] opened 2019-11-29 10:39 UTC
Hi,

when a pipeline is executed, tekton currently retains the Pod used for the execution. Over time, this results in quite some Pods in the Completed phase - which might cause issues on other parts (e.g. https://github.com/grafana/loki/issues/1315). Is there a reason to keep the pods around or can they be safely deleted (thinking about logs, metrics, status information ...)?

Also regarding e.g. PipelineRuns or TaskRuns - the information that the pipeline was executed is for sure worth keeping. However, does this cause issues on the API Server once 1.000+, 10.000+ or even more entries are reached?

Thanks,
Fabian

**Comment by ImJasonH** [comment] 2019-12-02 15:10
This seems like a duplicate of #454 

Basically, we do have vague plans to persist execution history to some datastore outside of the cluster's etcd. This would also let us clean up the completed Pods etc.

Right now we only have a design proposal that summarizes to "persist execution history to some datastore outside of the cluster's etcd" 😄but I plan to prototype some things and add more detail to this soon.

**Closed by ImJasonH** 2019-12-02 15:10 UTC
