### ISSUE TITLE
git clone failed: exec: "git": executable file not found in $PATH

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/pipeline#887] opened 2019-05-21 15:13 UTC
# Expected Behavior

Git is available to perform a `s2i build git_repo` command

# Actual Behavior

The following is reported when the `s2i` client executes the build command in order to git clone the project

```

ERROR: Clone failed: source https://github.com/snowdrop/rest-http-example , target /tmp/s2i358685604/upload/src, with output ""
--
  | I0521 14:46:49.147949       9 clone.go:48] error: git clone failed: exec: "git": executable file not found in $PATH
  | Build failed
  | ERROR: An error occurred: exec: "git": executable file not found in $PATH
```

# Steps to Reproduce the Problem

1. Install ocp3
2. Install tekton : `oc apply -f https://storage.googleapis.com/tekton-releases/latest/release.yaml`
3. Execute the following bash script responsible to create a sa, grant it scc privilege, task, taskRun

https://github.com/snowdrop/openshift-infra/blob/66a6b9999e519cd9d817f35802d40625977ed99b/tekton-pipelines/s2i-jdk8/install-openshift.sh

4. Check the log of the taskrun pod created: `kubectl -n tekton logs s2i-springboot-example-pod-7f73f4 -c build-step-s2ibuild`

![Screenshot 2019-05-21 17 16 45](https://user-images.githubusercontent.com/463790/58108502-3e588e00-7bec-11e9-843a-3f4983aef1d0.png)

# Task definition

https://github.com/snowdrop/openshift-infra/blob/master/tekton-pipelines/s2i-jdk8/tasks/clone-build.yml#L25-L38

**Comment by vbatts** [comment] 2019-05-21 15:21
build container running is https://quay.io/repository/openshift-pipeline/buildah?tab=info, which is built using https://github.com/containers/buildah/blob/master/buildahimage/stable/Dockerfile
The issue looks similar to https://github.com/containers/buildah/issues/1523

**Comment by bobcatfish** [comment] 2019-05-21 16:44
Is it possible that [docker.io/kbaig/s2i:latest](https://github.com/snowdrop/openshift-infra/blob/66a6b9999e519cd9d817f35802d40625977ed99b/tekton-pipelines/s2i-jdk8/tasks/clone-build.yml#L8) doesn't have `git` installed?

**Comment by cmoulliard** [comment] 2019-05-21 16:47
This is why I requested to @khrm : `Where is the github repo containing your `kbaig/s2i` dockerfile ?` to verify that

**Comment by vbatts** [comment] 2019-05-21 16:51
The container image can be looked through without the Docker file, right?

**Comment by vbatts** [comment] 2019-05-21 20:57
@cmoulliard for the s2i image:
```shell
[vbatts@knob] {master} ~$ podman pull  docker.io/kbaig/s2i:latest 
Trying to pull docker://docker.io/kbaig/s2i:latest...Getting image source signatures
Copying blob 1dbcab28ce46 skipped: already exists
Copying blob 83ef92b73cf4 done
Copying blob 437d12ee3223 done
Copying blob 458bee728a9c done
Copying config afee3abd00 done
Writing manifest to image destination
Storing signatures
afee3abd004c9eea1178252f5f9560f9825db7ee74225087f8f06df6f638dfa2
[vbatts@knob] {master} ~$ podman create --name s2i !$
podman create --name s2i docker.io/kbaig/s2i:latest
7713067ffa91014893e79f5a99944c1f626ee9d5a1e5de9d769734fd47df15e3
[vbatts@knob] {master} ~$ podman export s2i > s2i.tar
[vbatts@knob] {master} ~$ podman rm s2i
7713067ffa91014893e79f5a99944c1f626ee9d5a1e5de9d769734fd47df15e3
[vbatts@knob] {master} ~$ tar tvf s2i.tar | grep -iw git
[vbatts@knob] {master} ~$ 
```

**Comment by dlorenc** [comment] 2019-05-25 14:32
Looks like git is missing. Closing this as a dupe of https://github.com/containers/buildah/issues/1523.
Please let me know if this should be reopened.

**Closed by dlorenc** 2019-05-25 14:32 UTC
