### ISSUE TITLE
Feautre Request - Workspace from PersistentVolumeClaimTemplate

### ISSUE THREAD

**Issue by cameronbraid** [tektoncd/pipeline#2218] opened 2020-03-12 04:53 UTC
I would like to be able to have workspace PVC's creation and deletion fully managed by tekton using a volume claim template.

Currently this is supported in Argo Workflow and is a very useful feature (https://github.com/argoproj/argo/blob/master/examples/README.md)

```
  volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
  - metadata:
      name: workdir                     # name of volume claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi                  # Gi => 1024 * 1024 * 1024
```

The PVC would be created when the pipeline is executed, and deleted afterwards

This would conceptually be comparable to an emptyDir volume, however with the ability to specify a storage class for the PVC and not relying on a folder on the host as emptyDir does.

The current drawback of the workspace PersistentVolumeClaim is that issues would arise if two pipelines run concurrently that use the same PVC

**Comment by sbwsg** [comment] 2020-03-12 11:25
Thanks for the feature request!  I'm going to close it as a duplicate of https://github.com/tektoncd/pipeline/issues/1986 since we're tracking this feature there.  I appreciate you mentioning the PVC template idea - I'd seen it discussed in the context of Stateful Sets previously but wasn't aware that Argo also supports them.  This is good info!

**Closed by sbwsg** 2020-03-12 11:25 UTC
