### ISSUE TITLE
Doc: How to replay a task

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/pipeline#897] opened 2019-05-23 06:03 UTC
## Doc feature - How to start/cancel/stop or replay a task/pipeline

The existing doc only explains how to cancel a `TaskRun` or `PipelineRun` but not how to remove a task or replay it.

So I propose to enhance the doc and to explain how to run/stop or cancel a taskRun/PipelineRun like also how to replay it

According to @hrishin, this is possible to replay a TaskRun using a `generatedName` but this feature is not documented at all (I think so)

**Comment by vdemeester** [comment] 2019-05-23 06:49
@cmouillard, thanks for the issue. The Run CRD (pipelinerun and taskrun) are not replayable, they are, in a sense, immutable. The only mutation you can do afterwards is cancellation. 

This is a bit related to this issue : https://github.com/tektoncd/pipeline/issues/685.

GenerateName is a kubernetes feature that allows you to apply your object (yaml, ..) with only a prefix for the name, letting the controller(s) generate a unique name with this prefix. This is something that should work with any CRDs in k8s. Documenting its usage in tekton pipeline is something we need to do indeed 😇

**Comment by bobcatfish** [comment] 2019-07-09 13:45
I'm closing this as a duplicate of #685 (also updated the title of #685 to make it a bit more clear that these are the same).

Re-open if I've missed something!

**Closed by bobcatfish** 2019-07-09 13:45 UTC
Labels: help wanted, kind/documentation
