### ISSUE TITLE
Possibility to create PVC at PipelineRun start and destroy when PipelineRun ends

### ISSUE THREAD

**Issue by tstmrk** [tektoncd/pipeline#2174] opened 2020-03-06 11:57 UTC
# Expected Behavior
It would be nice to have the possibility have a PVC setup when the `PipelineRun `starts and destroyed when the `PipelineRun `ends. In this way I could share a volume among the Tasks within the `PipelineRun`.

# Actual Behavior
Sometimes I want to create some files onto disk in the step 1 and use them in step 2. Right now I have to create a PVC myself.

# Additional Info
Implementation could be the same as volumeClaimTemplates in k8s'  `[StafefulSet]`(https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/)

This feature could also be applicable to `TaskRun`

**Comment by sbwsg** [comment] 2020-03-06 12:25
Thanks for the feedback!  This behaviour does happen when linking output pipeline resources to input pipeline resources, but it's not generally available outside of pipeline resources (yet).

We have an issue open to add ["Auto Workspaces"](https://github.com/tektoncd/pipeline/issues/1986) that are essentially this feature - a volume that is in some way templated which is spun up and automatically populates Task's workspaces. I'm going to close this issue as a duplicate of that one but will copy your comment about the volumeClaimTemplate over to that issue because I hadn't heard of these before and I think they could be a very useful reference point, thankyou!

**Closed by sbwsg** 2020-03-06 12:25 UTC

**Comment by tstmrk** [comment] 2020-03-06 12:37
Cool! Thanks for your comment!
