### ISSUE TITLE
Missing permissions while downloading bundles from Google Artifact Registry using v0.33.2 (was working in v0.32.0)

### ISSUE THREAD

**Issue by olegy2008** [tektoncd/pipeline#4687] opened 2022-03-17 16:27 UTC
After upgrading tekton-pipelines-controller from v0.32.0 to v0.33.2 it can't download bundles from the Google Artifact Registry. 
We use a separate k8s service account as default for pipelineruns, it has imagepullsecret with `.dockerconfigjson` inside.

# Expected Behavior
tekton-pipelines-controller downloads pipeline definition (bundle) from the Google Artifact Registry and creates pipelinerun (just like v0.32.0 did)

# Actual Behavior

```
Error retrieving pipeline for pipelinerun <namespace>/<name of pipelinerun>: error when listing pipelines for pipelineRun <name of pipelinerun>: GET https://us-east4-docker.pkg.dev/v2/token?scope=repository%3A<gcp-project-name>%2F<repo-path>%3Apull&service=us-east4-docker.pkg.dev: DENIED: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "<full-repo-path>"
```

# Steps to Reproduce the Problem

1. Create secret with .dockerconfigjson inside with enough permissions to download from the repo
2. Create serviceaccount and use this secret as ImagePullSecret
3. Create pipeline and publish it's bundle (preferably to Google Artifact Registry)
4. Create pipelinerun using ref to previously published bundle and using previously created serviceaccount
5. Observe an error in the tekton dashboard/tekton-pipelines-operator logs/pipelinerun status

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1503", GitCommit:"2c7bbda09a9b7ca78db230e099cf90fe901d3df8", GitTreeState:"clean", BuildDate:"2022-02-18T03:17:45Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Pipeline version: v0.33.2
```

I suspect this keychain generation, because k8schain was updated between v0.32.0 and v0.33.2 
https://github.com/tektoncd/pipeline/blob/6b5710c3242ce7c3e1e8b876b7d35316449f617a/pkg/reconciler/pipelinerun/resources/pipelineref.go#L58
K8schain was upgraded here:
https://github.com/tektoncd/pipeline/pull/4488

**Comment by mike-serchenia** [comment] 2022-03-17 16:58
> So the error message is a little interesting here, because it sounds like a `403` (you don't have the right permission), and not a `401` (we don't know who you are).
> 
> k8schain updates might be the cause, but I'd expect that to result in creds not being sent at all, or sent incorrectly, resulting in a `401`, not what we're seeing here.
> 
> Just in case it ends up mattering (unlikely), are you running in a GKE cluster, potentially with Workload Identity enabled? That might cause the k8schain change to select a different valid account than under v0.32.0, and the newly selected account might not have the right permissions.

Right, it's GKE with Workload Identity enabled. So yes if we add proper annotation to the KSA `tekton-pipeline-controller` it will work, but there is no way to alter the KSA via Tkn operator config.

**Comment by olegy2008** [comment] 2022-03-17 18:30
> That sounds like a reasonable feature request to me. In the meantime, if you add the annotation, does the Operator (or anything else) remove it for you? I think that might be the better way to go in general, since it means you're not storing registry credentials in a secret.

If you asking about annotation on tekton-controllers-operator service account (which is used by tekton-controllers-operator):

Tekton operator creates tekton-cotrollers-operator serviceaccount automatically (it's defined in the installerset), so to resolve this issue with permissions with v0.33.2 controller we added workload identity binding for tekton-pipelines/tekton-pipelines-controller service account + manually added annotation to the service account. 
Tekton operator v0.55.1 didn't remove that for a while (but maybe it didn't because there were no more updates in tektonconfig since so nothing triggered an update, so I think it might remove it, since service account definition is hardcoded in the installerset for a particular tektonpipeline version).
Eventually, we rolled back to v0.54.0 tekton operator version which installed tekton-pipelines-controller v0.32.0 where everything works as expected.

If you asking about annotation on serviceaccount which is used to run pipelineruns (lets call it tekton-build-bot):

It's not controlled by operator, it has workload identity configured (on the GCP side + has annotation).

**Comment by CameronHudson8** [comment] 2022-04-26 18:59
I had the same issue, although my use case is different. My use case is that I want Tekton to run an image from my GCP artifact registry.
```
resource "kubectl_manifest" "acceptance_test_run" {
  yaml_body = yamlencode({
    apiVersion = "tekton.dev/v1beta1"
    kind       = "Task"
    metadata = {
      name      = "acceptance-test-run"
      namespace = "tekton-pipelines"
    }
    spec = {
      params = [
        {
          name        = "acceptance-test-image"
          description = "The full acceptance test image name and tag"
        }
      ]
      steps = [
        {
          name  = "acceptance-test-run"
          image = "$(params.acceptance-test-image)"
        }
      ]
    }
  })
}

```

I was able to resolve it by manually annotating the `tekton-pipelines-controller` kubernetes service account, in order to link it to a Google service account that had a role with permission `artifactregistry.repositories.downloadArtifacts`.

However, I'm now facing a new problem, which is that the task exits successfully without running the `CMD` in the container image... 😕

**Comment by imjasonh** [comment] 2022-04-26 20:30
Just to clarify @CameronHudson8 , the issue you're seeing in https://github.com/tektoncd/pipeline/issues/4687#issuecomment-1110144643 is the same as you've reported in https://github.com/tektoncd/pipeline/issues/4794 correct?

If so I'd prefer to diagnose that issue over there to avoid confusion with this issue. If there's any overlap please let me know. (and thanks for letting me know!)

**Comment by CameronHudson8** [comment] 2022-04-26 20:58
@imjasonh You are absolutely correct, sorry for the confusion!

**Comment by olegy2008** [comment] 2022-07-13 06:16
Is there any updates?

**Comment by imjasonh** [comment] 2022-07-13 14:43
It sounds like the missing permissions issue was fixed in https://github.com/tektoncd/pipeline/issues/4687#issuecomment-1110144643 with:

> I was able to resolve it by manually annotating the `tekton-pipelines-controller` kubernetes service account, in order to link it to a Google service account that had a role with permission `artifactregistry.repositories.downloadArtifacts`.

I'll close this issue, feel free to respond if this is still an issue for anyone.

**Closed by imjasonh** 2022-07-13 14:43 UTC
Labels: kind/bug, priority/important-soon

**Comment by mike-serchenia** [comment] 2022-07-13 15:26
Manually adding annotations won't help, operator will rewrite it to default

**Comment by imjasonh** [comment] 2022-07-13 15:32
Thanks for clarifying. So the issue isn't specific to auth, it's just that the solution to the auth problem requires setting an annotation on the SA, and the Operator doesn't support that well. Is that correct?

If so, I'd suggest filing a new issue on the Operator, referencing this issue, covering the fact that SA annotations are overwritten by the Operator.

Does that make sense?

**Comment by mike-serchenia** [comment] 2022-07-13 15:35
https://github.com/tektoncd/operator/issues/905
