### ISSUE TITLE
missing a plain crd link

### ISSUE THREAD

**Issue by wibed** [tektoncd/pipeline#7550] opened 2024-01-09 13:27 UTC
i would like to install the crd's for the whole stack without having to reference 5 implementation of the same structure.

is there a crd bundle, ideally with a kustomization.yaml located i can reference to install crd's independent from any predetermined structure i have to pretend to follow?

**Comment by AlanGreene** [comment] 2024-03-25 00:38
This appears to be a duplicate of https://github.com/tektoncd/operator/issues/1927. Can you elaborate on your question @wibed ?

Each release of Tekton Pipelines provides a release.yaml with all the CRDs etc. included. If this isn't what you're looking for can you describe your use case / why this doesn't meet your needs? Thanks

**Comment by vdemeester** [comment] 2024-12-20 13:48
@wibed given there has been no answer for a while, I'll close. Feel free to reach out for me to re-open if need be.

**Closed by vdemeester** 2024-12-20 13:48 UTC
Labels: kind/bug

**Comment by kastl-ars** [comment] 2026-06-11 07:56
I would like to chime in on that. Having the CRDs and the "normal" resources in the same YAML file makes applying this via e.g. ArgoCD tricky.

From what I gathered so far: As CRDs tend to be really large, the usual "last-applied" annotation causes issues, as it normally contains the whole content of the object. But does not allow storing a whole CRD in there.

So those CRDs are always being shown as out of sync.

So splitting out the CRDs into a separate file would be really helpful. (Charts would be even nicer...)
