### ISSUE TITLE
Beta features in V1 for Integration and Examples Test

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5706] opened 2022-11-01 15:20 UTC
### Feature request

The beta feature in V1 needs to be specified. The respective flag values and directories need to be updated.

- feature flag table & gates
- plumbing for beta feature tests

_(please feel free to edit if missing)_

### Use case

In #5579 , the integration tests for bundle conversion to resolver needs beta/ alpha feature flags to be set.

For example, the following tests are failing in v1 examples without feature flags for non-alpha integration test.
https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5579/pull-tekton-pipeline-integration-tests/1587456476048265216

**Comment by lbernick** [comment] 2023-01-18 16:13
I think this is a duplicate of https://github.com/tektoncd/pipeline/issues/5734?

**Closed by lbernick** 2023-01-18 16:13 UTC
Labels: kind/feature
