### ISSUE TITLE
Taskrun failed to create pod if network policy is added. 

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#3154] opened 2020-09-01 07:50 UTC
I've a namespace ``` tekton ``` where I create task and taskruns. But after adding network policy, taskrun fails to create pod.

``` error:   failed to create task run pod "echo-hello-world-task-run": pods "echo-hello-world-task-run-pod-7cx77" is forbidden: unable to validate against any pod security policy: [spec.volumes[4]: Invalid value: "downwardAPI": downwardAPI volumes are not allowed to be used]. Maybe missing or invalid Task tekton/echo-hello-world ```

Note: A taskrun named ``` echo-hello-world ``` exists in ``` tekton ``` namespace. 

This is my network policy. ``` tekton-pipeline ```  & ``` tekton ``` namespaces have a label  ```role: klovercloud```

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allowed-namespaces
  namespace: tekton
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: klovercloud
  - from:
    - namespaceSelector:
        matchLabels:
          role: kube-system
  podSelector: {}
  policyTypes:
  - Ingress

```

**Comment by GregDritschler** [comment] 2020-09-01 15:24
Based on the error message it sounds like the problem is with the controller's pod security policy not allowing use of downward API volumes, not with the network security policy.  What Kubernetes platform are you using, openshift or something else?  How did you install Tekton?

**Comment by zeromsi** [comment] 2020-09-02 08:27
@GregDritschler  I am using kubernetes, I've installed tekton by following descriptor.

``` https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml ```

**Comment by GregDritschler** [comment] 2020-09-02 15:24
I would like to check a few things in your cluster.  Can you post the output of the following commands:
```
$ kubectl get podsecuritypolicy

$ kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o yaml
```

I suspect the tekton controller is using a PodSecurityPolicy that doesn't authorize use of downwardAPI volumes.

Tekton provides a PodSecurityPolicy for the controller but it doesn't authorize use of downwardAPI volumes.  I think it needs to be updated to do that.  @gabemontero @skaegi  do you see any problem with adding that?

There was another problem related to the controller's role binding not granting access to that PSP but that was fixed by #2966.

I was able to recreate the problem in an IBM-hosted cluster but it wasn't easy.  IBM provides default PSPs that grant access to downwardAPI volumes so the admission controller was using those policies.  I had to remove the downwardAPI volume from those PSPs and then the problem occurred.  I added downwardAPI to the tekton controller PSP and it worked again.

**Comment by gabemontero** [comment] 2020-09-02 16:44
> I would like to check a few things in your cluster. Can you post the output of the following commands:
> 
> ```
> $ kubectl get podsecuritypolicy
> 
> $ kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o yaml
> ```
> 
> I suspect the tekton controller is using a PodSecurityPolicy that doesn't authorize use of downwardAPI volumes.
> 
> Tekton provides a PodSecurityPolicy for the controller but it doesn't authorize use of downwardAPI volumes. I think it needs to be updated to do that. @gabemontero @skaegi do you see any problem with adding that?

I'm good with that @GregDritschler

I would consider these volumes valid for the PSP:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- secret

> 
> There was another problem related to the controller's role binding not granting access to that PSP but that was fixed by #2966.
> 
> I was able to recreate the problem in an IBM-hosted cluster but it wasn't easy. IBM provides default PSPs that grant access to downwardAPI volumes so the admission controller was using those policies. I had to remove the downwardAPI volume from those PSPs and then the problem occurred. I added downwardAPI to the tekton controller PSP and it worked again.

**Comment by zeromsi** [comment] 2020-09-05 04:39
@GregDritschler 

``` kubectl get podsecuritypolicy ```

``` 
00-rook-privileged   true    SYS_ADMIN   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            configMap,downwardAPI,emptyDir,persistentVolumeClaim,secret,projected,hostPath,flexVolume
privileged           true    *           RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
psp.restricted       false               RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   true             configMap,emptyDir,secret,persistentVolumeClaim
tekton-pipelines     false               RunAsAny   RunAsAny           MustRunAs   MustRunAs   false            emptyDir,configMap,secret
````

```
kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o yaml
```
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      cni.projectcalico.org/podIP: 10.244.33.29/32
      cni.projectcalico.org/podIPs: 10.244.33.29/32
      kubernetes.io/psp: privileged
    creationTimestamp: "2020-08-28T15:58:02Z"
    generateName: tekton-pipelines-controller-676ff889cf-
    labels:
      app: tekton-pipelines-controller
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: controller
      app.kubernetes.io/part-of: tekton-pipelines
      app.kubernetes.io/version: v0.15.2
      pipeline.tekton.dev/release: v0.15.2
      pod-template-hash: 676ff889cf
      version: v0.15.2
    name: tekton-pipelines-controller-676ff889cf-9k6mh
    namespace: tekton-pipelines
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: tekton-pipelines-controller-676ff889cf
      uid: 35a109ea-d2af-41bb-b1c8-ca2e2ed67c78
    resourceVersion: "738735"
    selfLink: /api/v1/namespaces/tekton-pipelines/pods/tekton-pipelines-controller-676ff889cf-9k6mh
    uid: c6d97375-2f44-4558-a317-5a73e8fbd23a
  spec:
    containers:
    - args:
      - -kubeconfig-writer-image
      - klovercloud/tektoncd-pipeline-cmd-kubeconfigwriter:v0.15.2
      - -creds-image
      - klovercloud/tektoncd-pipeline-cmd-creds-init:v0.15.2
      - -git-image
      - klovercloud/tektoncd-pipeline-cmd-git-init:v0.15.2
      - -entrypoint-image
      - klovercloud/tektoncd-pipeline-cmd-entrypoint:v0.15.2
      - -nop-image
      - klovercloud/tektoncd-pipeline-cmd-nop:v0.15.2
      - -imagedigest-exporter-image
      - klovercloud/tektoncd-pipeline-cmd-imagedigestexporter:v0.15.2
      - -pr-image
      - klovercloud/tektoncd-pipeline-cmd-pullrequest-init:v0.15.2
      - -build-gcs-fetcher-image
      - klovercloud/tektoncd-pipeline-cmd-gcs-fetcher:v0.15.2
      - -gsutil-image
      - klovercloud/gcloud-sdk
      - -shell-image
      - klovercloud/tektoncd-distroless-base
      env:
      - name: SYSTEM_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: CONFIG_DEFAULTS_NAME
        value: config-defaults
      - name: CONFIG_LOGGING_NAME
        value: config-logging
      - name: CONFIG_OBSERVABILITY_NAME
        value: config-observability
      - name: CONFIG_ARTIFACT_BUCKET_NAME
        value: config-artifact-bucket
      - name: CONFIG_ARTIFACT_PVC_NAME
        value: config-artifact-pvc
      - name: CONFIG_FEATURE_FLAGS_NAME
        value: feature-flags
      - name: CONFIG_LEADERELECTION_NAME
        value: config-leader-election
      - name: METRICS_DOMAIN
        value: tekton.dev/pipeline
      image: klovercloud/tektoncd-pipeline-cmd-controller:v0.15.2
      imagePullPolicy: Always
      name: tekton-pipelines-controller
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/config-logging
        name: config-logging
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: tekton-pipelines-controller-token-nzmns
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: test-worker-1
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: tekton-pipelines-controller
    serviceAccountName: tekton-pipelines-controller
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: config-logging
      name: config-logging
    - name: tekton-pipelines-controller-token-nzmns
      secret:
        defaultMode: 420
        secretName: tekton-pipelines-controller-token-nzmns
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-08-28T15:58:02Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-08-28T15:58:10Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2020-08-28T15:58:10Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-08-28T15:58:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://671cd1603854fdc5e927d2326a93271d9c0d6d4351e5ea65fb8da3d00435b453
      image: klovercloud/tektoncd-pipeline-cmd-controller:v0.15.2
      imageID: docker-pullable://klovercloud/tektoncd-pipeline-cmd-controller@sha256:a26839a8fab19457649ee64aa3cb4818c93f5734c93cd2c1fdf2591da9964d5f
      lastState: {}
      name: tekton-pipelines-controller
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2020-08-28T15:58:09Z"
    hostIP: 95.217.107.251
    phase: Running
    podIP: 10.244.33.29
    podIPs:
    - ip: 10.244.33.29
    qosClass: BestEffort
    startTime: "2020-08-28T15:58:02Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by GregDritschler** [comment] 2020-09-15 20:13
That's strange.  The controller pod was validated with the `privileged` PSP per the `kubernetes.io/psp: privileged` annotation.  That PSP allows all volume types per the output of `kubectl get podsecuritypolicy`.  So I don't understand how the reported error of the controller not being able to create a pod that uses a downwardAPI volume is happening.  @gabemontero Am I missing something here?  I still think the tekton PSP needs to be updated but I'm not sure based on this that it's the problem here.

**Comment by gabemontero** [comment] 2020-09-15 20:45
Not that I can tell @GregDritschler 

The network policy must be getting in the way somehow of the pod security policy stuff in a unexpected way, per the cause and effect noted in the description.  As I took the description, it runs fine with PSP on and NP off.

I'm unfamiliar with networks policies.  Per the doc at https://kubernetes.io/docs/concepts/services-networking/network-policies/#prerequisites which pointed me to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/ it is an alpha level feature even as far out as 1.19.

Unexpectedness with alpha level features is not unheard of.

I tried some searches around using PSP and NP in conjunction but did not find anything of note.

But again, feels more like a k8s issue than a tekton one.

**Comment by skaegi** [comment] 2020-09-23 19:00
The tekton-pipelines-controller and tekton-pipelines-webhook both need to have an egress to the api server. Something like...
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: only-allow-egress-to-apiserver
  namespace: tekton-pipelines
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
         cidr: 172.20.0.1/32
    ports:
    - port: 2040
      protocol: TCP
```

It's likely different in your cluster, but If you look at the `kubernetes` service in the default namespace you can get the correct values ipBlock and port values from the service Endpoint. e.g.
```
Simons-MBP:~ skaegi$ kubectl describe service kubernetes
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                172.21.0.1
Port:              https  443/TCP
TargetPort:        2040/TCP
Endpoints:         172.20.0.1:2040
Session Affinity:  None
Events:            <none>
```

**Closed** 2021-05-07 10:40 UTC
Labels: kind/question, lifecycle/rotten
