### ISSUE TITLE
All container of pipline pod will pull image always

### ISSUE THREAD

**Issue by dragon9783** [tektoncd/pipeline#1343] opened 2019-09-23 03:01 UTC
# Expected Behavior
for offline environment, can NOT connect internat
if image (creds-init, entrypoint, webhook,bash etc) present on node, NOT pull image always

# Actual Behavior
pull image always
# Steps to Reproduce the Problem

1. install pipline
2. create task
3. create taskrun

# Additional Info

**Comment by vdemeester** [comment] 2019-11-07 18:22
/kind feature
/assign

This is the case because the default value for `ImagePullPolicy` is `Always`, preparing a fix for that

**Comment by vdemeester** [comment] 2019-11-08 09:53
@dragon9783 actually, according to the default value to the ImagePullPolicy, it's `Always` if the image tag is `:latest`, `IfNotPresent` otherwise. So it shouldn't affect the internal images for sure (as they should have a version of a digest).

The problem is that, as of today, k8s consider an image with a digest to have the `latest` tag (which is.. wrong I think).

**Comment by vdemeester** [comment] 2020-03-16 13:51
As this issues stalled, I am going to close it. @dragon9783 feel free to comment if this is still an issue.

/close

**Closed by vdemeester** 2020-03-16 13:51 UTC
Labels: kind/question
