### ISSUE TITLE
Any reason set "TaskRunResults" only when the "taskrun" succeed

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#3568] opened 2020-11-30 13:25 UTC
# Expected Behavior
Always set the `TaskRuResult` although the `Taskrun` failed.
Sometimes, the failed `task` want to deliver message by `result`
# Actual Behavior
Set `TaskRuResult` when `Taskrun` success

# Additional Info
See the code snippet:
https://github.com/tektoncd/pipeline/blob/4fdd018d4b54b5cbd44cf03fd1450ef727942e3e/pkg/pod/status.go#L162-L165
- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by sbwsg** [comment] 2020-11-30 15:13
We've discussed a bit here: https://github.com/tektoncd/pipeline/issues/3439

Personally I think that returning a failure message from a Task is a distinct use-case that shouldn't be a "result" but happy to discuss further!  I'm going to close this as a duplicate of #3439

**Closed by sbwsg** 2020-11-30 15:13 UTC
Labels: kind/bug
