### ISSUE TITLE
resoruce output paths not effective,resource not copy from /workspace/workspace to /custom

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/pipeline#4036] opened 2021-06-12 04:01 UTC
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: volume-task
spec:
  resources:
    inputs:
      - name: workspace
        type: git
    outputs:
      - name: workspace
        type: git
  steps:
    - name: build-war
      image: busybox
      script: |
        #!/bin/sh
        tar -cvf projectname.war /workspace/workspace
      volumeMounts:
        - name: custom-volume
          mountPath: /custom
    - name: ls
      image: busybox
      script: |
        #!/bin/sh
        ls /custom
      volumeMounts:
        - name: custom-volume
          mountPath: /custom
```

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: volume-taskrun-
spec:
  taskRef:
    name: volume-task
  resources:
    inputs:
      - name: workspace
        resourceRef:
          name: workspace-java
    outputs:
      - name: workspace
        paths:
          - /custom/workspace/
        resourceRef:
          name: workspace-java
  podTemplate:
    volumes:
      - name: custom-volume
        emptyDir: {}
```

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: workspace-java
spec:
  type: git
  params:
  - name: url
    value: https://github.com/skeeto/sample-java-project.git
  - name: revision
    value: master
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
- Tekton Pipeline version:
[root@master01 paths]# tkn version
Client version: 0.18.0
Pipeline version: v0.24.1
Triggers version: v0.14.2
Dashboard version: v0.17.0
```

**Comment by afrittoli** [comment] 2021-06-17 10:33
@13567436138 Thank you for your bug report.

I would kindly ask you to follow the bug template when filing issues:
- keep the title short and descriptive of the issue
- include expected behaviour and actual behaviour, with enough text to clearly describe what is the issue

**Comment by afrittoli** [comment] 2021-06-17 10:40
I suspect that the behaviour you're seeing may be related to a recent change in [release v0.24.0](https://github.com/tektoncd/pipeline/releases/tag/v0.24.0). From the release notes:

> # Deprecation Notices

> * :rotating_light: The  `disable-home-env-overwrite`  and `disable-working-dir-overwrite` are now deprecated (#3878)

> The default value of these flags has been changed to `true`. The flags are still available so that the old behaviour can still be configured; the flags are now deprecated and will be removed in 9 months from now.  [e-mail thread](https://groups.google.com/g/tekton-dev/c/C-PL8VYN51E)

The e-mail thread include several example that should help you solving the issue.

**Comment by bobcatfish** [comment] 2021-07-16 23:51
Closing this for now since it sounds like this is related to the change that @afrittoli  mentioned but please re-open if that's not the case.

**Closed by bobcatfish** 2021-07-16 23:51 UTC
Labels: kind/bug
