### ISSUE TITLE
git-clone cluster tasks throwing permission denied public key when using ssh basic-auth

### ISSUE THREAD

**Issue by bharathvenkatrajan** [tektoncd/pipeline#3221] opened 2020-09-14 09:55 UTC
# Expected Behavior
`git-clone` and `git-clonev0-14-3` cluster tasks to clone the private gitlab repository into the output workspace.
# Actual Behavior
`git-clone` and `git-clonev0-14-3` cluster tasks are throwing `Permission denied error (public key)` error with Gitlab while using `ssh basic-auth`.
```
{"level":"error","ts":1600075644.453436,"caller":"git/git.go:41","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force master]: exit status 128\nWarning: Permanently added the ECDSA host key for IP address '10.12.13.14 to the list of known hosts.\r\n\n    ***********************************************************************\n    * Access to this computer system is limited to authorised users only. *\n    * Unauthorised users may be subject to prosecution under the Crimes*\n\n\nLoad key \"/tekton/home/.ssh/id_gitlab-creds\": invalid format\r\ngit@git.company.com: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,keyboard-interactive).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\t/opt/app-root/src/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:41\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\t/opt/app-root/src/go/src/github.com/tektoncd/pipeline/pkg/git/git.go:119\nmain.main\n\t/opt/app-root/src/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:203"}
{"level":"fatal","ts":1600075644.4535692,"caller":"git-init/main.go:53","msg":"Error fetching git repository: failed to fetch [master]: exit status 128","stacktrace":"main.main\n\t/opt/app-root/src/go/src/github.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:203"}
```
# Steps to Reproduce the Problem

1. Do as seen in this example here - https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/taskruns/git-ssh-creds-without-known_hosts.yaml

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0+724e12f93f", GitCommit:"d5465d715197862b15c8cf05e864d7c3cfea6917", GitTreeState:"clean", BuildDate:"2019-10-10T22:03:41Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+08c38ef", GitCommit:"08c38ef", GitTreeState:"clean", BuildDate:"2020-07-30T18:43:47Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
 Client version: 0.12.0
 Pipeline version: v0.14.3
 Triggers version: v0.6.1
```
- Openshift pipelines operator `version 1.1.1`

Secret
```
kind: Secret
apiVersion: v1
metadata:
  name: gitlab-creds
  namespace: my-namespace
  selfLink: /api/v1/namespaces/my-namespace/secrets/gitlab-creds

  annotations:
    tekton.dev/git-0: git.company.com
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2020-09-14T09:26:36Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:ssh-privatekey': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:tekton.dev/git-0': {}
        'f:type': {}
data:
  ssh-privatekey: >-
    LS0V....
type: kubernetes.io/ssh-auth
```

Pipeline
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  managedFields:
    - apiVersion: tekton.dev/v1beta1
  name: restart-vm
  namespace: my-namespace
spec:
  params:
    - default: ''
      description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: ''
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
  tasks:
    - name: git-clone-v0-14-3
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone-v0-14-3
      workspaces:
        - name: output
          workspace: my-workspace
  workspaces:
    - name: my-workspace
```
PipelineRun

```
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: restart-vm-$(uid)
    spec:
      params:
      - name: git-url
        value: git@git.company.com:my-group/my-project.git
      - name: git-revision
        value: master
      pipelineRef:
        name: restart-vm
      serviceAccountName: my-bot
      workspaces:
      - name: my-workspace
        persistentvolumeclaim:
          claimName: my-pvc
```
My service account `my-bot` is also linked with the secret `gitlab-creds`. 

I tested the ssh-keys doing a `git clone git@git.company.com:my-group/my-project.git` manually in the cli and it works perfectly fine. So, I'm guessing this is a bug?

**Comment by sbwsg** [comment] 2020-09-14 14:11
This error message gives me pause: `Load key \"/tekton/home/.ssh/id_gitlab-creds\": invalid format`

Is it possible that this is happening because you're using `data` instead of `stringData` in the Secret?

**Comment by bharathvenkatrajan** [comment] 2020-09-14 23:39
@sbwsg When I put in the `ssh private key` in a `Source Secret` in openshift, it automatically encodes it with base64 and creates this Secret YAML for me. Moreover, `stringData` is plain text, since its a private key, isn't using `data` more secure?

**Comment by sbwsg** [comment] 2020-09-15 13:56
Initially I think we just need to figure out if this is the core of the problem or not.  Unfortunately I'm not familiar with openshift so can't provide much help there.  But my hunch is that the encoded `data` field is possibly the reason that the `invalid format` error is being given.

All Tekton does is expose your Secrets to the container.  It doesn't do any kind of encoding/decoding of the SSH key.  So an error about the formatting of the credential implies, to me, something wrong in the encoding before it gets to Tekton.

**Comment by sbwsg** [comment] 2020-10-26 17:52
@bharathvenkatrajan just wanted to check in here: did you ever manage to resolve this problem?  Were you able to figure out if there were indeed encoding issues or another root cause?

**Comment by bharathvenkatrajan** [comment] 2020-10-26 21:53
@sbwsg apologies for the late reply. I tried to debug more but was still getting the same error. So i switched to http auth.

**Comment by chmouel** [comment] 2021-01-25 08:10
/remove-lifecycle stale
/lifecycle frozen

Related https://github.com/tektoncd/pipeline/issues/3712

**Comment by muxmuse** [comment] 2021-03-16 16:56
I received the error message `Load key \"/tekton/home/.ssh/id_gitlab-creds\": invalid format` when a newline was missing at the end of `-----END OPENSSH PRIVATE KEY-----`

**Comment by CurryWurry** [comment] 2021-03-25 09:39
@muxmuse You are a lifesaver.. took me 3 hours and your post pointed my to the solution. Thanks for sharing!

**Comment by sbwsg** [comment] 2021-05-04 17:05
It appears that this issue is related to formatting errors in the private key.  I'm going to close this for the time being since we don't have really good steps to reproduce nor evidence that it's a Tekton-specific problem. If someone stumbles across this in future and is able to pinpoint a specific problem in Pipelines then feel free to re-open!

**Closed by sbwsg** 2021-05-04 17:05 UTC
Labels: kind/bug, lifecycle/frozen

**Comment by mishraprafful** [comment] 2023-03-16 15:06
@chmouel I would request to re-open this issue as we are facing this on pipelines version `0.40.2`.

Few pointers that might help in understanding and resolving the issue:
* We have tried to use the OPENSSH key outside the context of tekton and it works with or without the newline character at the end. 
* These keys are generated without a trailing EOL character, and we have to explicitly add a `\n` for this to work in a tekton task.
* The above statements are tested in [git-clone task](https://hub.tekton.dev/tekton/task/git-clone) from [Tekton Hub](https://hub.tekton.dev) and a custom own task, both show the same results.

[This](https://tekton.dev/vault/pipelines-v0.40.x/auth/#configuring-ssh-auth-authentication-for-git) is the guide followed to mount a `kubernetes.io/ssh-auth` secret to the service account used in tekton pipeline.
