### ISSUE TITLE
Unable to push image to private docker registry if URL is not using the default 443 port

### ISSUE THREAD

**Issue by hollisc** [tektoncd/pipeline#992] opened 2019-06-19 19:31 UTC
# Expected Behavior
Built image to be pushed to private docker registry.

# Actual Behavior
The "build-step-build-and-push" step fails in the TaskRun of the tutorial (https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md) if using a private docker registry using a different port than 443.  From the error message, it appears to be complaining about the `:` in the image URL. 

The error from the step is: 

```
error pushing image: getting tag for destination: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: /<IP of Private Registry>:8500/tekton-pipelines/leeroy-web
```

# Steps to Reproduce the Problem

1. Install Tekton on an existing Kubernetes cluster (https://github.com/tektoncd/pipeline/blob/master/docs/install.md). 
2. Run through tutorial to build and push an image (https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#pipeline) to a private docker registry.  When creating the TaskRun resource, run fails on the "build-step-build-and-push" step.

Here is the yaml of the PipelineResource for Image resource: 

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
spec:
  type: image
  params:
    - name: url
      value: https://<IP Address>:8500/tekton-pipelines/leeroy-web
```

**Comment by vincent-pli** [comment] 2019-06-20 00:28
Seems the issue is caused by docker itself,

> The Repository Name needs to be unique in that namespace, can be two to 255 characters, and can only contain lowercase letters, numbers or - and _.

Come from https://docs.docker.com/docker-hub/repos/

**Comment by vdemeester** [comment] 2019-06-20 11:10
@hollisc the issue is in the PipelineResource definition. The `url` parameter of the image pipeline resource might not be that well named… It has to be the **image reference**, which means it should not include transport (`https://`). In your case, it should be `value: <IP Address>:8500/tekton-pipelines/leeroy-web`.

I feel this field might need to be renamed.

**Comment by hollisc** [comment] 2019-06-20 13:00
Hi @vdemeester, thanks for clarifying this as that is what I had initially set.

If I set `url` parameter to `<IP Address>:8500/tekton-pipelines/leeroy-web`, I get this TaskRun error for the "build-step-build-and-push" step.  The docker registry is enabled for https only.  I tried updating the `--docker-server` field in the sa-tekton-pipelines secret to include https but no luck yet.

```
kubectl logs build-docker-image-from-git-source-icp-task-run-15-pod-669883 -c build-step-build-and-push -n tekton-pipelines

error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "<IP Address>:8500/tekton-pipelines/leeroy-web:latest": Get http://<IP Address>:8500/v2/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

**Comment by vdemeester** [comment] 2019-06-20 13:24
@hollisc interesting, I am not sure why `kaniko` tries to push on `http` :thinking:. As it's a private repository, I am guessing you need to be authenticate. Did you add an authentication serviceaccount (see [`auth.md](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md)) to your TaskRun (or PipelineRun) ?

**Comment by hollisc** [comment] 2019-06-20 18:55
@vdemeester, yes I added serviceaccount with basic-auth secret containing registry credentials.  
Also, verified the credentials does exist in /builder/home/.docker/config.json using the executor:debug image.

```
{"auths":{"https://<IP Address>:8500":{"username":"admin","password":"<admin pwd>","auth":"<Encoded user:pwd>","email":"not@val.id"}}}
```

How does kaniko know to use `http` vs `https`?   Should it reference the server in the docker config.json?

**Comment by yangkailc** [comment] 2019-06-21 03:23
@hollisc kaniko uses flags to know http protocol will be used when  pushing to  insecure registry，you can try "insecure-pull" and "insecure"  flag in "build-step-build-and-push"  step。

**Comment by hollisc** [comment] 2019-06-21 15:56
Hi @yangkailc and @vdemeester, if I add "--skip-tls-verify" arg, the TaskRun is able to push the image to the private registry successfully.  Seems like there is an issue why kaniko is trying to push with `http` instead of `https`.

**Comment by vdemeester** [comment] 2019-11-07 15:53
@hollisc I'm gonna go ahead and close this issue as it seems to be fixed for you *and* it's on kaniko side :angel: 

/close

**Closed by vdemeester** 2019-11-07 15:53 UTC
Labels: good first issue, help wanted, kind/bug
