### ISSUE TITLE
When creating a pipeline with a condition that has missing attributes the pipeline never progresses but no error is given

### ISSUE THREAD

**Issue by utherp0** [tektoncd/pipeline#1610] opened 2019-11-25 08:07 UTC
# Expected Behavior
When starting a pipelinerun where the condition contains missing information, such as a parameter type field, the status of the pipelinerun via the Operator should be set to failed

# Actual Behavior

Pipelinerun status never gets updated, user has to examine the Operator Logs to get information on Condition processing failure

# Steps to Reproduce the Problem

1. Create a condtion with a param but do not give it a type
2. Create a pipeline that uses the condition and set the param appropriately
3. Create a pipelinerun that runs the pipeline

# Additional Info
Example condition (broken):

apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: condition1
spec:
  params:
    - name: "path"
  check:
    image: alpine
    command: ["/bin/sh"]
    args: ['-c', 'test -f $(params.path)']

Example condition (fixed):

apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: condition1
spec:
  params:
    - name: "path"
      type: string
  check:
    image: alpine
    command: ["/bin/sh"]
    args: ['-c', 'test -f $(params.path)']

**Comment by vincent-pli** [comment] 2019-11-26 00:55
The issue is gone with v0.8.0 or latest master.

**Comment by dibyom** [comment] 2019-11-27 01:16
Yeah I think this should be fixed by https://github.com/tektoncd/pipeline/pull/1431 which is in the 0.8 release. Maybe the operator installation is using an older release?

**Comment by vincent-pli** [comment] 2019-11-27 01:49
@dibyom 
That's true,  the issue has gone in Operator, since we start to use v0.8.0

**Comment by vdemeester** [comment] 2019-11-27 09:12
Alright, if it's fixed with 0.8.0, we can close this one then
/close

**Closed by vdemeester** 2019-11-27 09:12 UTC
Labels: kind/question
