### ISSUE TITLE
Is there any field setting to automatically remove these pods

### ISSUE THREAD

**Issue by bibi520** [tektoncd/pipeline#1589] opened 2019-11-19 06:37 UTC
![image](https://user-images.githubusercontent.com/42456284/69122537-0cac7b00-0ada-11ea-9548-c11f47ff4128.png)
Is there any field setting to automatically remove these pods

**Comment by sbwsg** [comment] 2019-11-19 14:14
Hey @bibi520, there's no setting to automatically clean up the pods. To remove the pods you can delete the PipelineRuns that created them. There are a couple reasons for this but the main one I can think of right now is that the logs from your PipelineRun are stored attached to the pods by Kubernetes. So if you want to see those logs we need (right now) to keep those pods alive. If you want to clean up the pods created by a PipelineRun then you can delete that PipelineRun.  This will delete all the associated pods.

See https://github.com/tektoncd/pipeline/issues/1302 for a report of the same problem. I'm going to close this question as a duplicate of #1302 but please feel free to keep the conversation going on that issue. Cheers!

**Closed by sbwsg** 2019-11-19 14:14 UTC
