### ISSUE TITLE
Pod disruption budget: tekton-pipelines-webhook issue

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/pipeline#3759] opened 2021-02-12 12:39 UTC
Hi, experienced this w/ 0.18.1 on Azure AKS during an rolling upgrade of k8s on the cluster via AKS's platform.

I was having troubles not being able to upgrade any cluster; AKS provisions a new node, drains one then upgrades and on and on. The entire process was hanging and failing, and it turned out due to the PodDisruptionBudget for `tekton-pipelines-webhook`. Is this expected? What should be the recommended procedure for avoiding this situation? Deleting the PDB prior to these kind of operations?

```
Name:           tekton-pipelines-webhook
Namespace:      tekton-pipelines
Min available:  80%
Selector:       app.kubernetes.io/component=webhook,app.kubernetes.io/instance=default,app.kubernetes.io/name=webhook,app.kubernetes.io/part-of=tekton-pipelines
Status:
    Allowed disruptions:  0
    Current:              1
    Desired:              1
    Total:                1
Events:                   <none>
```

**Comment by bitsofinfo** [comment] 2021-02-12 12:53
or i guess just scaling it prior to an upgrade would solve it

**Comment by ImJasonH** [comment] 2021-02-12 13:15
Duplicate of #3654 -- I'll comment over there

**Closed by ImJasonH** 2021-02-12 13:15 UTC
