### ISSUE TITLE
not compact go1.17 and k8s.io/api v0.23.0

### ISSUE THREAD

**Issue by ycyxuehan** [tektoncd/pipeline#4417] opened 2021-12-13 08:13 UTC
kubernetes: v1.23.0
go：1.17.5
go mod:

go 1.17
replace sigs.k8s.io/controller-runtime v0.10.4 => /root/go/pkg/mod/sigs.k8s.io/controller-runtime
require (
	github.com/tektoncd/pipeline v0.30.0
	github.com/tektoncd/triggers v0.17.1
	k8s.io/api v0.23.0
	k8s.io/apimachinery v0.23.0
	k8s.io/client-go v0.23.0
	sigs.k8s.io/controller-runtime v0.10.4
)

#### use master branch of controller-runtime to compact go 1.17
logs:
# github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:116:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:145:11: cannot use ref("k8s.io/api/core/v1.Toleration") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:154:8: cannot use ref("k8s.io/api/core/v1.Affinity") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:160:8: cannot use ref("k8s.io/api/core/v1.PodSecurityContext") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:177:11: cannot use ref("k8s.io/api/core/v1.Volume") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:207:8: cannot use ref("k8s.io/api/core/v1.PodDNSConfig") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:239:11: cannot use ref("k8s.io/api/core/v1.LocalObjectReference") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:253:11: cannot use ref("k8s.io/api/core/v1.HostAlias") (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:276:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:334:8: cannot use ref("github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1.CloudEventDel...) (type "k8s.io/kube-openapi/pkg/validation/spec".Ref) as type "github.com/go-openapi/spec".Ref in field value
/root/go/pkg/mod/github.com/tektoncd/pipeline@v0.30.0/pkg/apis/pipeline/v1beta1/openapi_generated.go:334:8: too many errors

**Comment by lbernick** [comment] 2021-12-13 20:11
This looks like a duplicate of #4320

**Comment by jerop** [comment] 2022-01-10 20:40
closing as duplicate of https://github.com/tektoncd/pipeline/issues/4320

**Closed by jerop** 2022-01-10 20:40 UTC
Labels: kind/bug
