### ISSUE TITLE
Expose init errors in the dashboard

### ISSUE THREAD

**Issue by EnriqueL8** [tektoncd/pipeline#1705] opened 2019-12-09 11:44 UTC
# Expected Behavior
If an error occurs during the init phase for a pipeline, that error needs to be printed out in the status tab for that pipeline.

# Actual Behavior
My pipeline had the following error:
```
invalid value "docker-secret=https://index.docker.io/v1/" for flag -basic-docker: Multiple entries for url: https://index.docker.io/v1/
```
In order to find this error, I had to get the logs for one of the init containers within the pipeline pod, as such:
```
kubectl logs <pipeline-pod> -c step-credential-initializer
```
I had no idea which init container had errored out. 

My pipeline task status just says: `waiting: reason: PodInitializing` instead of printing the init error.

# Steps to Reproduce the Problem

1. Create two secrets with the same url (or anything that makes the init phase error)
2. Create a pipeline run
3. Look at the dashboard status tab

**Comment by vdemeester** [comment] 2019-12-09 12:17
@EnriqueL8 thanks for the issue. There is two issues at place there I feel

1. The fact that the pipeline task status says `waiting: reason: PodInitializing`, as, looking at the error above, it should be failed. Did it stays like this forever or did it got marked as a failure ? (this issue would be in here)
2. The fact that the dashboard doesn't display errors from the init container in the status, which would be an issue in `tektoncd/dashboard`

/kind bug

**Comment by EnriqueL8** [comment] 2019-12-09 13:56
Hi @vdemeester, it stayed `waiting: reason: PodInitializing` forever. Yes, I believe there is an issue open for the dashboard aswell.

**Comment by vdemeester** [comment] 2019-12-09 14:00
@EnriqueL8 :+1:

**Comment by vdemeester** [comment] 2020-07-24 13:51
@EnriqueL8 not sure if it's still an issue. I'm gonna go ahead and close the issue because I feel it might be fixed. If you can reproduce this on recent version of tekton, please feel free to comment it here and I'll re-open :wink:

**Closed by vdemeester** 2020-07-24 13:51 UTC
Labels: kind/bug
