### ISSUE TITLE
tkn - could not find the requested resource

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#5804] opened 2022-11-27 23:26 UTC
Running [these][1] examples, when getting to:

    tkn pipelinerun logs hello-goodbye-run -f -n default

I get this error:

    Error: the server could not find the requested resource (get pipelineruns.tekton.dev hello-goodbye-run)

The pipeline is there:

    kubectl get pipelinerun -A
    NAMESPACE   NAME                SUCCEEDED   REASON      STARTTIME   COMPLETIONTIME
    default     hello-goodbye-run   True        Succeeded   9h 

  [1]: https://tekton.dev/docs/getting-started/pipelines/

**Comment by Yongxuanzhang** [comment] 2022-11-30 03:48
Hi, could you provide more details like your tkn version, Tekton pipeline version?
I cannot reproduce this issue.

**Comment by JCzz** [comment] 2022-11-30 06:55
Thanks.

```
tkn version
Client version: 2020-04-01T10:57:38Z
Pipeline version: unknown
```

I dont know how to get the pipeline version

**Comment by AlanGreene** [comment] 2022-11-30 10:13
That's a very old `tkn` version, you could also try `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'` or manually inspect the labels on the controller to find the version.

**Comment by vdemeester** [comment] 2022-11-30 10:27
@JCzz are you running OpenShift ? (if yes `tkn version -n openshift-pipelines` might help). In any case, as @AlanGreene said, this is a very old `tkn` version. It might only support "talking to" `v1alpha1` API, and you might run a cluster where there is only `v1beta1` API for tektoncd/pipeline.

Ideally, you should probably get the latest version of `tkn` 👼🏼

**Comment by JCzz** [comment] 2023-02-24 00:03
Thanks Hi @vdemeester 

Not running OpenShift, I will try updating tkn

**Comment by max3ndeavour** [comment] 2023-05-30 10:03
Hi,
Any progress on this ? 
I'm on a Mac, installed TKN and kubectl

`
tkn version
Client version: 0.11.0. 
Pipeline version: v0.48.0 
Triggers version: unknown 

kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
`

Here are the steps followed: 
`
kubectl apply -f checkout.yaml

kubectl apply -f pipeline_init.yaml

kubectl apply -f pipeline_init_run.yaml

kubectl get pipelines -A

tkn pipeline start pipeline --showlog -p repo-url="myGitRepo"
`

**Comment by AlanGreene** [comment] 2023-05-30 10:23
Hi @max3ndeavour, it looks like you're running a very old version of the Tekton CLI:
> Client version: 0.11.0.

That was released in July 2020, almost 3 years ago.

The latest release is [v0.31.0](https://github.com/tektoncd/cli/releases/tag/v0.31.0), can you try upgrading and testing again?

**Closed** 2023-07-29 15:12 UTC
Labels: kind/bug, priority/awaiting-more-evidence, lifecycle/rotten
